services:
  - type: web
    name: gestion-bancaire
    env: docker
    dockerfilePath: ./docker/Dockerfile
    buildCommand: |
      echo "Build completed"
    startCommand: supervisord -c /etc/supervisor/conf.d/supervisord.conf
    autoDeploy: true
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: LOG_CHANNEL
        value: stderr
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file

  - type: pgsql
    name: banking-db
    ipAllowList: []
    plan: free

  - type: redis
    name: banking-redis
    ipAllowList: []
    plan: free
