[supervisord]
nodaemon=true
logfile=/var/www/storage/logs/supervisord.log
pidfile=/var/www/supervisord.pid
user=www-data

[program:laravel-scheduler]
command=/usr/bin/php /var/www/artisan schedule:run >> /dev/null 2>&1
directory=/var/www
autostart=true
autorestart=true
numprocs=1
startsecs=0
stopwaitsecs=3
stdout_logfile=/var/www/storage/logs/scheduler.log
stderr_logfile=/var/www/storage/logs/scheduler.err.log

[program:laravel-queue]
command=/usr/bin/php /var/www/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
directory=/var/www
autostart=true
autorestart=true
numprocs=2
process_name=%(program_name)s_%(process_num)02d
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/queue-worker-%(process_num)02d.log
